modLoader = "javafml"
loaderVersion = "[43,)"
#updateJSONURL=""
issueTrackerURL = "https://github.com/AppliedEnergistics/Applied-Mekanistics/issues"
displayURL = "https://github.com/AppliedEnergistics/Applied-Mekanistics#readme"
logoFile = "logo.png"
#credits="Thanks for this example mod goes to Java"
authors = "ramidzkh"
license = "See GitHub repository for details"

[[mods]]
modId = "appmek"
version = "${version}"
displayName = "Applied Mekanistics"
description = "Use Mekanism resources through your ME network"
updateJSONURL = "https://api.modrinth.com/updates/applied-mekanistics/forge_updates.json"

[[dependencies.appmek]]
modId = "forge"
mandatory = true
versionRange = "[47.0.0,48.0.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.appmek]]
modId = "ae2"
mandatory = false
versionRange = "[15.0.0,16.0.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.appmek]]
modId = "mekanism"
mandatory = true
versionRange = "[10.3.9,11.0.0)"
ordering = "AFTER"
side = "BOTH"
